version: "3"

services:
  php:
    build: ./docker/.
    container_name: php_arquitectura_avanzada
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    networks:
      - arquitecturacurso
  db: 
    image: mysql
    container_name: mysql_arquitectura_avanzada
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - arquitecturacurso
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_arquitectura_avanzada
    ports:
      - "3005:80" #comparte la misma red que php
    depends_on:
      - db
    environment:
      - PNA_ARBITRARY=1
      - PNA_HOST=db
      - PNA_USER=root
      - #faltan variables
    networks:
      - arquitecturacurso

networks:
  arquitecturacurso:
    name: arquitecturacurso
    driver: bridge